import "./globals.css";

import { manrope } from "@/lib/typography";

export const metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>{children}</body>
    </html>
  );
}
